apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-config
  namespace: netbox-actividad3
data:
  ALLOWED_HOSTS: "*"
  DB_HOST: netbox-postgresql
  DB_PORT: "5432"
  DB_NAME: netbox
  DB_USER: netbox
  DEBUG: "False"
  LOGIN_REQUIRED: "true"
  MEDIA_ROOT: /opt/netbox/netbox/media
  REDIS_HOST: netbox-redis-master
  REDIS_CACHE_HOST: netbox-redis-master
  REDIS_PORT: "6379"
  REDIS_CACHE_PORT: "6379"
  REDIS_DATABASE: "0"
  REDIS_CACHE_DATABASE: "1"
  SUPERUSER_EMAIL: admin@example.com
  SUPERUSER_NAME: admin
  REMOTE_AUTH_ENABLED: "False"
  REMOTE_AUTH_BACKEND: ""
  REMOTE_AUTH_AUTO_CREATE_USER: "False"
